--SQL Advance Case Study


--Q1--BEGIN 
	select [STATE],YEAR([DATE]),IDMODEL,IDCUSTOMER from DIM_LOCATION T3
	left join FACT_TRANSACTIONS T6
	on T3.IDLocation = T6.IDLocation
	WHERE YEAR([DATE]) > 2005 AND QUANTITY>0
	GROUP BY [STATE],YEAR([DATE]),IDMODEL,IDCUSTOMER
	
--Q1--END

--Q2--BEGIN
    SELECT [STATE],SUM(QUANTITY) AS SALES_CNT FROM DIM_LOCATION T3
	LEFT JOIN FACT_TRANSACTIONS T6
	ON T3.IDLocation = T6.IDLocation
	LEFT JOIN DIM_MODEL T5
	ON T6.IDModel = T5.IDModel
	WHERE COUNTRY='US' AND IDManufacturer = 12
	GROUP BY [STATE]
	ORDER BY SUM(QUANTITY) DESC

--Q2--END

--Q3--BEGIN      
    SELECT IDMODEL,ZIPCODE,[STATE],SUM(QUANTITY) AS TRANSACTIONS FROM DIM_LOCATION T3
	LEFT JOIN FACT_TRANSACTIONS T6
	ON T3.IDLocation = T6.IDLocation
	WHERE QUANTITY>0
	GROUP BY IDMODEL,ZIPCODE,[STATE]

--Q3--END

--Q4--BEGIN
 SELECT TOP 1 MODEL_NAME,UNIT_PRICE FROM DIM_MODEL
 ORDER BY Unit_price 

--Q4--END

--Q5--BEGIN

SELECT Manufacturer_Name,T5.IDModel,SUM(QUANTITY) AS SALES_QUANTITY,AVG(TOTALPRICE) AS AVG_PRICE FROM FACT_TRANSACTIONS T6
LEFT JOIN DIM_MODEL T5
ON T6.IDModel = T5.IDModel
LEFT JOIN DIM_MANUFACTURER T4
ON T5.IDManufacturer = T4.IDManufacturer
WHERE Manufacturer_Name IN (SELECT TOP 5 Manufacturer_Name FROM FACT_TRANSACTIONS T6
      LEFT JOIN DIM_MODEL T5
      ON T6.IDModel = T5.IDModel
      LEFT JOIN DIM_MANUFACTURER T4
      ON T5.IDManufacturer = T4.IDManufacturer
      GROUP BY Manufacturer_Name 
	  ORDER BY SUM(TOTALPRICE) DESC)
GROUP BY Manufacturer_Name,T5.IDModel
ORDER BY AVG(TOTALPRICE) DESC

--Q5--END

--Q6--BEGIN
SELECT CUSTOMER_NAME,AVG(TOTALPRICE) AS AVG_PRICE,[YEAR] FROM DIM_CUSTOMER T1
LEFT JOIN FACT_TRANSACTIONS T6
ON T1.IDCustomer = T6.IDCustomer
LEFT JOIN DIM_DATE T2
ON T6.[Date] = T2.[DATE]
WHERE [YEAR] = 2009
GROUP BY CUSTOMER_NAME,[YEAR] 
HAVING AVG(TOTALPRICE)>500

--Q6--END
	
--Q7--BEGIN  
SELECT * FROM(
SELECT TOP 5 IDMODEL FROM FACT_TRANSACTIONS T6
LEFT JOIN DIM_DATE T2
ON T6.[Date] = T2.[DATE]
WHERE [YEAR] =2008
GROUP BY IDMODEL	
ORDER BY SUM(QUANTITY) DESC) AS FIRST_T
INTERSECT
SELECT * FROM(
SELECT TOP 5 IDMODEL FROM FACT_TRANSACTIONS T6
LEFT JOIN DIM_DATE T2
ON T6.[Date] = T2.[DATE]
WHERE [YEAR] =2009
GROUP BY IDMODEL,[YEAR]	
ORDER BY SUM(QUANTITY) DESC) AS SECOND_T
INTERSECT
SELECT * FROM(
SELECT TOP 5 IDMODEL FROM FACT_TRANSACTIONS T6
LEFT JOIN DIM_DATE T2
ON T6.[Date] = T2.[DATE]
WHERE [YEAR] =2010
GROUP BY IDMODEL,[YEAR]	
ORDER BY SUM(QUANTITY) DESC) AS THIRD_T

--Q7--END	
--Q8--BEGIN

SELECT * FROM (
SELECT IDMANUFACTURER,SUM(TotalPrice) AS SALES,[YEAR] FROM DIM_MODEL T5
LEFT JOIN FACT_TRANSACTIONS T6
ON T5.IDModel = T6.IDModel
LEFT JOIN DIM_DATE T2
ON T6.[Date] = T2.[DATE]
WHERE [YEAR] =2009
GROUP BY IDMANUFACTURER,[YEAR]
ORDER BY SALES DESC
OFFSET 1 ROWS
FETCH NEXT 1 ROWS ONLY ) AS FIRST_T
UNION 
SELECT * FROM (
SELECT IDMANUFACTURER,SUM(TotalPrice) AS SALES,[YEAR] FROM DIM_MODEL T5
LEFT JOIN FACT_TRANSACTIONS T6
ON T5.IDModel = T6.IDModel
LEFT JOIN DIM_DATE T2
ON T6.[Date] = T2.[DATE]
WHERE [YEAR] =2010
GROUP BY IDMANUFACTURER,[YEAR]
ORDER BY SALES DESC
OFFSET 1 ROWS
FETCH NEXT 1 ROWS ONLY) AS SECOND_T


--Q8--END
--Q9--BEGIN
SELECT * FROM (
SELECT IDMANUFACTURER FROM DIM_MODEL T5
LEFT JOIN FACT_TRANSACTIONS T6
ON T5.IDModel = T6.IDModel	
LEFT JOIN DIM_DATE T2
ON T6.[Date] = T2.[DATE]
WHERE [YEAR] = 2010
GROUP BY IDMANUFACTURER) AS FIRST_T
EXCEPT
SELECT * FROM (
SELECT IDMANUFACTURER FROM DIM_MODEL T5
LEFT JOIN FACT_TRANSACTIONS T6
ON T5.IDModel = T6.IDModel	
LEFT JOIN DIM_DATE T2
ON T6.[Date] = T2.[DATE]
WHERE [YEAR] = 2009
GROUP BY IDMANUFACTURER) AS SECOND_T

--Q9--END

--Q10--BEGIN
SELECT AVG_SPEND,[YEAR] FROM(
	   SELECT IDCUSTOMER,[YEAR],AVG(TOTALPRICE) AS AVG_SPEND,AVG(QUANTITY) AS QTY FROM FACT_TRANSACTIONS T6
	   LEFT JOIN DIM_DATE T2
	   ON T6.[Date] = T2.[DATE] 
	   WHERE IDCUSTOMER IN (SELECT TOP 10 IDCUSTOMER FROM FACT_TRANSACTIONS 
							 GROUP BY IDCUSTOMER
							 ORDER BY SUM(TOTALPRICE) DESC) 
       GROUP BY IDCUSTOMER,[YEAR]
       ORDER BY IDCUSTOMER,[YEAR] ) 
ORDER BY [YEAR]
OFFSET 1 ROWS
FETCH NEXT 53 ROWS ONLY  

--Q10--END
	